const GITHUBEVENTS = [
	'check_run',
	'check_suite',
	'code_scanning_alert',
	'commit_comment',
	'content_reference',
	'create',
	'delete',
	'deploy_key',
	'deployment',
	'deployment_status',
	'discussion',
	'discussion_comment',
	'fork',
	'github_app_authorization',
	'gollum',
	'installation',
	'issue_comment',
	'issues',
	'label',
	'marketplace_purchase',
	'member',
	'membership',
	'milestone',
	'organization',
	'org_block',
	'package',
	'page_build',
	'ping',
	'project_card',
	'project_column',
	'project',
	'public',
	'pull_request',
	'pull_request_review',
	'pull_request_review_comment',
	'push',
	'release',
	'repository_dispatch',
	'repository',
	'repository_import',
	'repository_vulnerability_alert',
	'secret_scanning_alert',
	'security_advisory',
	'sponsorship',
	'star',
	'status',
	'team',
	'watch',
	'workflow_dispatch',
	'workflow_run',
];

const GITLABEVENTS = [
	'Push Hook',
	'Issue Hook',
	'Merge Request Hook',
	'Wiki Page Hook',
	'Job Hook',
	'Deployment Hook',
	'Tag Push Hook',
	'Note Hook',
	'Pipeline Hook',
	'Feature Flag Hook',
	'Release Hook',
];

const BITBUCKETEVENTS = [
	'repo:push',
	'repo:fork',
	'repo:updated',
	'repo:transfer',
	'repo:commit_comment_created',
	'repo:commit_status_created',
	'repo:commit_status_updated',
	'issue:created',
	'issue:updated',
	'issue:comment_created',
	'pullrequest:created',
	'pullrequest:updated',
	'pullrequest:changes_request_created',
	'pullrequest:changes_request_removed',
	'pullrequest:approved',
	'pullrequest:unapproved',
	'pullrequest:fulfilled',
	'pullrequest:rejected',
	'pullrequest:comment_created',
	'pullrequest:comment_updated',
	'pullrequest:comment_deleted',
];

const SENTRYEVENTS = [
	'installation',
	'uninstallation',
	'event_alert',
	'metric_alert',
	'issue',
	'error',
];

const CLICKUPEVENTS = [
	'taskCreated',
	'taskUpdated',
	'taskDeleted',
	'taskPriorityUpdated',
	'taskStatusUpdated',
	'taskAssigneeUpdated',
	'taskDueDateUpdated',
	'taskTagUpdated',
	'taskMoved',
	'taskCommentPosted',
	'taskCommentUpdated',
	'taskTimeEstimateUpdated',
	'taskTimeTrackedUpdated',
	'listCreated',
	'listUpdated',
	'listDeleted',
	'folderCreated',
	'folderUpdated',
	'folderDeleted',
	'spaceCreated',
	'spaceUpdated',
	'spaceDeleted',
	'goalCreated',
	'goalUpdated',
	'goalDeleted',
	'keyResultCreated',
	'keyResultUpdated',
	'keyResultDeleted',
];

const JIRAEVENTS = [
	'jira:issue_created',
	'jira:issue_updated',
	'jira:issue_deleted',
	'issue_property_set',
	'issue_property_deleted',
	'worklog_created',
	'worklog_updated',
	'worklog_deleted',
	'comment_created',
	'comment_updated',
	'comment_deleted',
	'attachment_created',
	'attachment_deleted',
	'project_created',
	'project_updated',
	'project_deleted',
	'project_soft_deleted',
	'project_restored_deleted',
	'project_archived',
	'project_restored_archived',
	'user_created',
	'user_updated',
];

const EXTRAJIRAEVENTS = [
	'user_deleted',
	'option_issuelinks_changed',
	'option_subtasks_changed',
	'option_attachments_changed',
	'option_issuelinks_changed',
	'option_timetracking_changed',
	'option_unassigned_issues_changed',
	'option_watching_changed',
	'option_voting_changed',
	'sprint_updated',
	'sprint_created',
	'sprint_updated',
	'sprint_started',
	'sprint_closed',
	'board_deleted',
	'board_created',
	'board_updated',
	'board_configuration_changed',
	'jira_expression_evaluation_failed',
	'jira:version_released',
	'jira:version_unreleased',
	'jira:version_created',
	'jira:version_moved',
	'jira:version_updated',
	'jira:version_deleted',
	'issuelink_created',
	'issuelink_deleted',
];

const ZENDESKEVENTS = ['ticket_solved'];

const ASANAEVENTS = ['assignee', 'custom_fields', 'name'];

const EXTRAASANAEVENTS = [
	'due_on',
	'due_at',
	'dependencies',
	'dependents',
	'task',
	'notes',
	'html_notes',
	'completed',
	'completed_at',
	'likes',
	'approval_status',
	'resource_subtype',
	'start_on',
	'start_at',
];

// in trello update card includes - action_renamed_card,action_move_card_from_list_to_list,action_marked_the_due_date_complete,action_board_perm_level (changing the visiblity of the board),action_update_board_name
const TRELLOEVENTS = ['updateCard', 'createCard', 'addMemberToCard'];

const MONDAY_EVENTS = ['create_pulse', 'update_name', 'update_column_value'];

module.exports = {
	GITHUBEVENTS,
	GITLABEVENTS,
	BITBUCKETEVENTS,
	SENTRYEVENTS,
	CLICKUPEVENTS,
	JIRAEVENTS,
	ZENDESKEVENTS,
	ASANAEVENTS,
	TRELLOEVENTS,
	MONDAY_EVENTS,
};
